### ISSUE TITLE
Feature request: vmagent static scrape config via custom resource

### ISSUE THREAD

**Issue by zigmund** [VictoriaMetrics/operator#155]
According to [additional-scrape.MD](https://github.com/VictoriaMetrics/operator/blob/master/docs/additional-scrape.MD), the only way to add static scrape config into vmagent is additionalScrapeConfigs with secret, containing scrape config.

This implementation is rigid and doesn't allow complex configurations.

It will be much better to maintain static scrape configs via custom resource like VMPodScrape etc. (VMStaticScrape?)

**Comment by f41gh7** [comment]
hm, something like: 
```yaml

spec:
 targetEndpoints:
 -  targets: [10.10.1.1:8031]
    labels: 
     label: value
 - targets: [192.168.15.1:9100]
 scheme: http
 relabelConfigs: []
 basicAuth: {}
 tlsConfig: {}
 params: {}
 ....
```

**Comment by zigmund** [comment]
@f41gh7 yes, looks good.

**Comment by f41gh7** [comment]
FYI, VMStaticScrape was added at master branch, can you verify, that it works as expected? My initial tests was successful.

**Comment by zigmund** [comment]
@f41gh7 we're currently at version 0.7.1 with heavily modified manifests, so need some time to adopt master to our cluster.

**Comment by zigmund** [comment]
@f41gh7 tested with minimal configuration.
Created vmstaticscrape, updated configuration - vmagent scrapes metrics as expected.

But found a bug: deleted vmstaticscrape resouce from cluster, but vmagent's config (secret) remains same, so vmagent continues to scrape targets from deleted manifest.

Operator logs on resource deletion:
```
{"level":"info","ts":1614341505.2124999,"logger":"controllers.VMStaticScrape","msg":"Reconciling VMStaticScrape","vmservicescrape":"debug/test"}
{"level":"info","ts":1614341505.212687,"logger":"controllers.VMStaticScrape","msg":"found vmagent objects ","vmservicescrape":"debug/test","len: ":2}
{"level":"info","ts":1614341505.2127347,"logger":"controllers.VMStaticScrape","msg":"reconciled VMStaticScrape","vmservicescrape":"debug/test","vmagent":"common","vmagent":"linkerd"}
```

Generated config with vmstaticscrape and after deletion:
```
zigmund@bug:~$ kubectl -n monitoring get secret vmagent-common -o json | jq -r '.data["vmagent.yaml.gz"]' | base64 -d | gunzip
...
- job_name: debug/test/0
  static_configs:
  - targets:
    - target1:9283
    - target2:9283
    - target3:9283
    labels:
      bar: baz
      some: foo
  relabel_configs: []
...
```

Maybe other resources' deletion doesn't updated vmagent config too, didn't tested.

**Comment by f41gh7** [comment]
Thanks! Found old bug with deletionTimestamp, it wasn't respected by list items request. Should be fixed now.

**Comment by zigmund** [comment]
Tested with fresh master image - resource deletion still not respected.

**Comment by f41gh7** [comment]
There was another issue with selectors match, now it should be ok.

**Comment by zigmund** [comment]
Tested with `victoriametrics/operator@sha256:facfc6513f99c57c02867cab7ab9885908addacc73b765ef34de59a44388dc4d` - same here.

**Comment by f41gh7** [comment]
Sorry, latest commit must fix. In case of object deletion heuristic failed to match objects.

**Comment by zigmund** [comment]
@f41gh7 works now, thanks.

**Comment by f41gh7** [comment]
Added to the latest release v0.10.0
