### ISSUE TITLE
VMAgent stuck in reconcile loop

### ISSUE THREAD

**Issue by micke** [VictoriaMetrics/operator#1589]
I just deployed my first `VMAgent` via the operator running in helm chart `0.55.3` but it seem to be stuck in a reconcile loop:

```json5
{"level":"info","ts":"2025-10-30T23:37:47Z","logger":"controller.VMAgent","msg":"object has changes with previous state, applying changes","vmagent":"victoria-metrics","namespace":"victoria-metrics"}
{"level":"info","ts":"2025-10-30T23:37:47Z","logger":"controller.VMAgent","msg":"updating Deployment vmagent-victoria-metrics configurationis_prev_equal=false,is_current_equal=false,is_prev_nil=false, prev_spec_diff={v1.DeploymentSpec}.Template.Spec.InitContainers[0].Image:-\"victoriametrics/operator:config-reloader-v0.62.0\" +\"quay.io/prometheus-operator/prometheus-config-reloader:v0.82.1\",{v1.DeploymentSpec}.Template.Spec.InitContainers[0].Command:-\"nil\" +\"[/bin/sh]\",{v1.DeploymentSpec}.Template.Spec.InitContainers[0].Args[0]:-\"--reload-url=http://localhost:8429/-/reload\" +\"-c\",{v1.DeploymentSpec}.Template.Spec.InitContainers[0].Args[1]:-\"--config-envsubst-file=/etc/vmagent/config_out/vmagent.env.yaml\" +\"gunzip -c /etc/vmagent/config/vmagent.yaml.gz > /etc/vmagent/config_out/vmagent.env.yaml\",{v1.DeploymentSpec}.Template.Spec.InitContainers[0].Args[?->2]:-\"--config-secret-name=victoria-metrics/vmagent-victoria-metrics\" +\"nil\",{v1.DeploymentSpec}.Template.Spec.InitContainers[0].Args[?->3]:-\"--config-secret-key=vmagent.yaml.gz\" +\"nil\",{v1.DeploymentSpec}.Template.Spec.InitContainers[0].Args[?->4]:-\"--only-init-config\" +\"nil\",{v1.DeploymentSpec}.Template.Spec.InitContainers[0].VolumeMounts[0->?]:-\"nil\" +\"{config false <nil> /etc/vmagent/config  <nil> }\",{v1.DeploymentSpec}.Template.Spec.Containers[0].Image:-\"victoriametrics/operator:config-reloader-v0.62.0\" +\"quay.io/prometheus-operator/prometheus-config-reloader:v0.82.1\",{v1.DeploymentSpec}.Template.Spec.Containers[0].Command:-\"nil\" +\"[/bin/prometheus-config-reloader]\",{v1.DeploymentSpec}.Template.Spec.Containers[0].Args[2]:-\"--config-secret-name=victoria-metrics/vmagent-victoria-metrics\" +\"--config-file=/etc/vmagent/config/vmagent.yaml.gz\",{v1.DeploymentSpec}.Template.Spec.Containers[0].Args[?->3]:-\"--config-secret-key=vmagent.yaml.gz\" +\"nil\",{v1.DeploymentSpec}.Template.Spec.Containers[0].VolumeMounts[1->?]:-\"nil\" +\"{config false <nil> /etc/vmagent/config  <nil> }\",{v1.DeploymentSpec}.Template.Spec.Containers[1].Image:-\"victoriametrics/vmagent:v1.128.0\" +\"victoriametrics/vmagent:v1.125.0\", curr_spec_diff={v1.DeploymentSpec}.Template.Spec.InitContainers[0].Image:-\"quay.io/prometheus-operator/prometheus-config-reloader:v0.82.1\" +\"victoriametrics/operator:config-reloader-v0.62.0\",{v1.DeploymentSpec}.Template.Spec.InitContainers[0].Args[0]:-\"-c\" +\"--reload-url=http://localhost:8429/-/reload\",{v1.DeploymentSpec}.Template.Spec.InitContainers[0].Args[1]:-\"gunzip -c /etc/vmagent/config/vmagent.yaml.gz > /etc/vmagent/config_out/vmagent.env.yaml\" +\"--config-envsubst-file=/etc/vmagent/config_out/vmagent.env.yaml\",{v1.DeploymentSpec}.Template.Spec.InitContainers[0].Args[2->?]:-\"nil\" +\"--config-secret-name=victoria-metrics/vmagent-victoria-metrics\",{v1.DeploymentSpec}.Template.Spec.InitContainers[0].Args[3->?]:-\"nil\" +\"--config-secret-key=vmagent.yaml.gz\",{v1.DeploymentSpec}.Template.Spec.InitContainers[0].Args[4->?]:-\"nil\" +\"--only-init-config\",{v1.DeploymentSpec}.Template.Spec.InitContainers[0].VolumeMounts[?->0]:-\"{config false <nil> /etc/vmagent/config  <nil> }\" +\"nil\",{v1.DeploymentSpec}.Template.Spec.Containers[0].Image:-\"quay.io/prometheus-operator/prometheus-config-reloader:v0.82.1\" +\"victoriametrics/operator:config-reloader-v0.62.0\",{v1.DeploymentSpec}.Template.Spec.Containers[0].Args[2]:-\"--config-file=/etc/vmagent/config/vmagent.yaml.gz\" +\"--config-secret-name=victoria-metrics/vmagent-victoria-metrics\",{v1.DeploymentSpec}.Template.Spec.Containers[0].Args[3->?]:-\"nil\" +\"--config-secret-key=vmagent.yaml.gz\",{v1.DeploymentSpec}.Template.Spec.Containers[0].Ports:-\"nil\" +\"[{reloader-http 0 8435 TCP }]\",{v1.DeploymentSpec}.Template.Spec.Containers[0].VolumeMounts[?->1]:-\"{config false <nil> /etc/vmagent/config  <nil> }\" +\"nil\",{v1.DeploymentSpec}.Template.Spec.Containers[0].LivenessProbe:-\"nil\" +\"&Probe{ProbeHandler:ProbeHandler{Exec:nil,HTTPGet:&HTTPGetAction{Path:/health,Port:{0 8435 },Host:,Scheme:HTTP,HTTPHeaders:[]HTTPHeader{},},TCPSocket:nil,GRPC:nil,},InitialDelaySeconds:0,TimeoutSeconds:1,PeriodSeconds:10,SuccessThreshold:1,FailureThreshold:3,TerminationGracePeriodSeconds:nil,}\",{v1.DeploymentSpec}.Template.Spec.Containers[0].ReadinessProbe:-\"nil\" +\"&Probe{ProbeHandler:ProbeHandler{Exec:nil,HTTPGet:&HTTPGetAction{Path:/health,Port:{0 8435 },Host:,Scheme:HTTP,HTTPHeaders:[]HTTPHeader{},},TCPSocket:nil,GRPC:nil,},InitialDelaySeconds:5,TimeoutSeconds:1,PeriodSeconds:10,SuccessThreshold:1,FailureThreshold:3,TerminationGracePeriodSeconds:nil,}\",{v1.DeploymentSpec}.Template.Spec.Containers[1].Image:-\"victoriametrics/vmagent:v1.125.0\" +\"victoriametrics/vmagent:v1.128.0\"","vmagent":"victoria-metrics","namespace":"victoria-metrics"}
{"level":"info","ts":"2025-10-30T23:37:47Z","logger":"controller.VMAgent","msg":"object was successfully reconciled","vmagent":"victoria-metrics","namespace":"victoria-metrics"}
```

The `VMAgent` in question:

```yaml
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAgent
metadata:
  name: victoria-metrics
spec:
  port: "8429"

  remoteWrite:
  - url: http://vmsingle-victoria-metrics:8428/api/v1/write

```

The operator is deployed via argocd and kustomize
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: victoria-metrics

helmCharts:
  - name: victoria-metrics-operator
    releaseName: victoria-metrics-operator
    repo: https://victoriametrics.github.io/helm-charts
    version: 0.55.3
    includeCRDs: true
    namespace: victoria-metrics
    valuesInline:
      global:
        cluster:
          dnsDomain: cluster.localdomain
      admissionWebhooks:
        enabled: true
        certManager:
          enabled: true
      podSecurityContext:
        runAsNonRoot: true
        runAsUser: 1022
        runAsGroup: 1022
        fsGroup: 1022
```

This is the first time i'm deploying a VMAgent so i've not had one running before the change in `0.64.0` to the custom config reloader.

**Comment by micke** [comment]
Rolling back to helm chart `0.54.1` and operator version `0.63.0` stops the reconcile loop at least.

**Comment by AndrewChubatiuk** [comment]
fixed in operator 0.65.0 and in helm chart 0.55.0

**Comment by micke** [comment]
@AndrewChubatiuk Thanks, but unfortunately I'm still seeing the same issue with 0.65.0 and helm chart 0.55.0:

```json5
{"level":"info","ts":"2025-10-31T21:48:25Z","logger":"controller.VMAgent","msg":"object has changes with previous state, applying changes","vmagent":"victoria-metrics","namespace":"victoria-metrics"}
{"level":"info","ts":"2025-10-31T21:48:25Z","logger":"controller.VMAgent","msg":"updating Deployment vmagent-victoria-metrics configurationis_prev_equal=false,is_current_equal=false,is_prev_nil=false, prev_spec_diff={v1.DeploymentSpec}.Template.Spec.InitContainers[0].Image:-\"victoriametrics/operator:config-reloader-v0.62.0\" +\"quay.io/prometheus-operator/prometheus-config-reloader:v0.82.1\",{v1.DeploymentSpec}.Template.Spec.Containers[0].Image:-\"victoriametrics/operator:config-reloader-v0.62.0\" +\"quay.io/prometheus-operator/prometheus-config-reloader:v0.82.1\",{v1.DeploymentSpec}.Template.Spec.Containers[1].Image:-\"victoriametrics/vmagent:v1.128.0\" +\"victoriametrics/vmagent:v1.125.0\", curr_spec_diff={v1.DeploymentSpec}.Template.Spec.InitContainers[0].Image:-\"quay.io/prometheus-operator/prometheus-config-reloader:v0.82.1\" +\"victoriametrics/operator:config-reloader-v0.62.0\",{v1.DeploymentSpec}.Template.Spec.InitContainers[0].Args[0]:-\"-c\" +\"--reload-url=http://localhost:8429/-/reload\",{v1.DeploymentSpec}.Template.Spec.InitContainers[0].Args[1]:-\"gunzip -c /etc/vmagent/config/vmagent.yaml.gz > /etc/vmagent/config_out/vmagent.env.yaml\" +\"--config-envsubst-file=/etc/vmagent/config_out/vmagent.env.yaml\",{v1.DeploymentSpec}.Template.Spec.InitContainers[0].Args[2->?]:-\"nil\" +\"--config-secret-name=victoria-metrics/vmagent-victoria-metrics\",{v1.DeploymentSpec}.Template.Spec.InitContainers[0].Args[3->?]:-\"nil\" +\"--config-secret-key=vmagent.yaml.gz\",{v1.DeploymentSpec}.Template.Spec.InitContainers[0].Args[4->?]:-\"nil\" +\"--only-init-config\",{v1.DeploymentSpec}.Template.Spec.InitContainers[0].VolumeMounts[?->0]:-\"{config false <nil> /etc/vmagent/config  <nil> }\" +\"nil\",{v1.DeploymentSpec}.Template.Spec.Containers[0].Image:-\"quay.io/prometheus-operator/prometheus-config-reloader:v0.82.1\" +\"victoriametrics/operator:config-reloader-v0.62.0\",{v1.DeploymentSpec}.Template.Spec.Containers[0].Args[2]:-\"--config-file=/etc/vmagent/config/vmagent.yaml.gz\" +\"--config-secret-name=victoria-metrics/vmagent-victoria-metrics\",{v1.DeploymentSpec}.Template.Spec.Containers[0].Args[3->?]:-\"nil\" +\"--config-secret-key=vmagent.yaml.gz\",{v1.DeploymentSpec}.Template.Spec.Containers[0].Ports:-\"nil\" +\"[{reloader-http 0 8435 TCP }]\",{v1.DeploymentSpec}.Template.Spec.Containers[0].VolumeMounts[?->1]:-\"{config false <nil> /etc/vmagent/config  <nil> }\" +\"nil\",{v1.DeploymentSpec}.Template.Spec.Containers[0].LivenessProbe:-\"nil\" +\"&Probe{ProbeHandler:ProbeHandler{Exec:nil,HTTPGet:&HTTPGetAction{Path:/health,Port:{0 8435 },Host:,Scheme:HTTP,HTTPHeaders:[]HTTPHeader{},},TCPSocket:nil,GRPC:nil,},InitialDelaySeconds:0,TimeoutSeconds:1,PeriodSeconds:10,SuccessThreshold:1,FailureThreshold:3,TerminationGracePeriodSeconds:nil,}\",{v1.DeploymentSpec}.Template.Spec.Containers[0].ReadinessProbe:-\"nil\" +\"&Probe{ProbeHandler:ProbeHandler{Exec:nil,HTTPGet:&HTTPGetAction{Path:/health,Port:{0 8435 },Host:,Scheme:HTTP,HTTPHeaders:[]HTTPHeader{},},TCPSocket:nil,GRPC:nil,},InitialDelaySeconds:5,TimeoutSeconds:1,PeriodSeconds:10,SuccessThreshold:1,FailureThreshold:3,TerminationGracePeriodSeconds:nil,}\",{v1.DeploymentSpec}.Template.Spec.Containers[1].Image:-\"victoriametrics/vmagent:v1.125.0\" +\"victoriametrics/vmagent:v1.128.0\"","vmagent":"victoria-metrics","namespace":"victoria-metrics"}
{"level":"info","ts":"2025-10-31T21:48:28Z","logger":"controller.VMAgent","msg":"object was successfully reconciled","vmagent":"victoria-metrics","namespace":"victoria-metrics"}
```

**Comment by micke** [comment]
Well now i feel stupid, i apparently had another operator deployed that had not been cleaned up by argocd...

Sorry for the noise, it works great now...
