### ISSUE TITLE
Kubernetes 1.26 Compatibility

### ISSUE THREAD

**Issue by ruifung** [VictoriaMetrics/operator#583]
HorizontalPodAutoscaler in autoscaling/v2beta2 is no longer available, use autoscaling/v2.

```
cannot remove HPA for vmselect: no matches for kind "HorizontalPodAutoscaler" in version "autoscaling/v2beta2"
```

**Comment by rishid** [comment]
Just to add to this `PodSecurityPolicy` is deprecated as well which is used in `rbac.yml`

https://kubernetes.io/docs/concepts/security/pod-security-policy/

**Comment by f41gh7** [comment]
It's an issue with kubernetes API deprecation : 
```autoscaling/v2beta2 HorizontalPodAutoscaler is deprecated in v1.23+, unavailable in v1.26```

 Need to fix it.

**Comment by f41gh7** [comment]
> Am I correct in thinking that this is resolved as of [772151e](https://github.com/VictoriaMetrics/operator/commit/772151e592a454f9e38935108c434140f4a29c2b)?

Yes, forgot to mention it. It must be fixed at  [v0.30.4](https://github.com/VictoriaMetrics/operator/releases/tag/v0.30.4) release.

**Comment by Haleygo** [comment]
![image](https://user-images.githubusercontent.com/39937150/218962594-42731bb1-1060-45fe-933e-d4e40e32fd82.png)
Seems like the autoscaling/v2beta2 problem still not fixed in k8s 1.26+. Should use autoscaling/v2 when HPAV2Beta not supported in [here](https://github.com/VictoriaMetrics/operator/blob/master/controllers/factory/k8stools/version.go#L75
).
![image](https://user-images.githubusercontent.com/39937150/218963560-eef14b9e-23e1-4839-b0ca-31222cdf74ae.png)

**Comment by Haleygo** [comment]
@f41gh7 
Hi, is there any plan to releasev0.30.5 to include this fix?
